sources:
  - name: app_logs
    # Example: scan the rotated log file from the previous day
    path: "data/logs/app-${YYYY}-${MM}-${DD-1}.log"
  - name: proxy_logs
    path: "data/logs/proxy-${YYYY}-${MM}-${DD-1}.log"
rules:
  critical:
    - "FATAL"
    - "OutOfMemory"
    - "segmentation fault"
  high:
    - "ERROR"
    - "panic:"
  security:
    - "denied.*policy"
    - "SQL injection"
